services:
  postgres:
    container_name: sd_teste
    image: postgres:16.3-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/postgres

volumes:
  postgres_data:
